settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
      - group.system
      - group.automations



system:
  name: System
  entities:
    - sensor.time_template
    - sensor.since_last_boot_template
    - sensor.version

automations:
  name: Automations
  entities:
    - automation.alert_when_a_container_goes_offline
    - automation.furnace_filter_reminder
    - automation.lais_bedtime
    - automation.send_notification_upon_failed_login_attempt
    - automation.set_theme_at_startup
    - automation.trash_day_reminder
