settings:
  name: Settings
  view: yes
  icon: mdi:settings
  entities:
      - group.system
      - group.automation_alerts
      - group.automation_reminders
      - group.automation_misc



system:
  name: System
  entities:
    - sensor.time_template
    - sensor.since_last_boot_template
    - sensor.version

automation_alerts:
  name: Critical Alerts
  entities:
    - automation.alert_when_a_container_goes_offline
    - automation.send_notification_upon_failed_login_attempt
    - automation.lais_bedtime

automation_reminders:
  name: Reminders
  entities:
    - automation.trash_day_reminder
    - automation.furnace_filter_reminder

automation_misc:
  name: Misc
  entities:
    - automation.set_theme_at_startup
