- platform: rest
  resource: http://192.168.173.100:8126/containerstation/api/v1/container/docker/9a6adb55c5c0
  name: MQTT Server
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

- platform: rest
  resource: http://192.168.173.100:8126/containerstation/api/v1/container/docker/5857e1f0d533
  name: FuseNet Server
  body_on: '{"state": "start"}'
  body_off: '{"state": "stop"}'
  is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
